import 'package:musee_m1irt/models/bibliotheque_model.dart';
import 'package:musee_m1irt/models/moment_model.dart';
import 'package:musee_m1irt/models/musee_model.dart';
import 'package:musee_m1irt/models/ouvrage_model.dart';
import 'package:musee_m1irt/models/pays_model.dart';
import 'package:musee_m1irt/models/visiter_model.dart';
import 'package:musee_m1irt/repositories/bibliotheque_repository.dart';
import 'package:musee_m1irt/repositories/moment_repository.dart';
import 'package:musee_m1irt/repositories/musee_repository.dart';
import 'package:musee_m1irt/repositories/ouvrage_repository.dart';
import 'package:musee_m1irt/repositories/pays_repository.dart';
import 'package:musee_m1irt/repositories/visiter_repository.dart';

late final MuseeRepository museeRepository;
late final MomentRepository momentRepository;
late final PaysRepository paysRepository;
late final BibliothequeRepository bibliothequeRepository;
late final VisiterRepository visiterRepository;
late final OuvrageRepository ouvrageRepository;
List<PaysModel> global_list_pays = [];
List<MuseeModel> global_list_musee = [];
List<MomentModel> global_list_moment= [];
List<VisiterModel> global_list_visiter= [];
List<OuvrageModel> global_list_ouvrage= [];
List<BibliothequeModel> global_list_bibliotheque= [];